# Generated by Django 4.1.6 on 2023-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series_info',
            name='series_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
