# Generated by Django 4.1.6 on 2023-03-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_series_info_series_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('championships', models.IntegerField()),
                ('notable_teams', models.CharField(max_length=100)),
                ('blurb', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('championships', models.IntegerField()),
                ('founded_date', models.DateField()),
                ('notable_players', models.CharField(max_length=100)),
                ('blurb', models.TextField()),
            ],
        ),
    ]
