# Generated by Django 4.1.6 on 2023-03-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_player_info_team_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_info',
            name='logo',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
