# Generated by Django 4.1.6 on 2023-03-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_team_info_major_wins_team_info_regional_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='series_info',
            name='team_one_logo',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='series_info',
            name='team_two_logo',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
